name: CI

on:
  push:
  pull_request:

jobs:
  ci:
    name: CI
    uses: silverstripe/gha-ci/.github/workflows/ci.yml@v1
    with:
      phpcoverage_force_off: true
      phplinting: false
      doclinting: false
      phpunit: true
